config/routes.rb
Rails.application.routes.draw do

  scope module: :public do

    resources :addresses,except:[:new,:show]

    get    'orders/new'
    post   'orders/confirm'
    get    'orders/completion'
    resources :orders,only:[:index,:create,:show]


    delete 'cart_items/erase_all' =>   "cart_items#erase"
    resources :cart_items,only:[:index,:create,:destroy,:update]

    patch  'customers/withdraw'
    get    'customers/mypage' =>       "customers#show"
    get    'customers/edit'
    patch  'customers' =>              "customers#update"
    get    'customers/unsubscribe'

    resources :items,only:[:index,:show]

    root to: "homes#top"
    get 'about' => "homes#about"
  end
  namespace :admin do
    resources :order_items,only:[:update]

    resources :orders,only:[:show,:update]

    resources :customers,except:[:destroy,:create,:new]

    resources :genres,except:[:destroy,:new,:show]

    resources :items,except:[:destroy]

    root to: "homes#top"
  end
  devise_for :customers, skip: [:passwords],controllers:{
    registrations:"public/registrations",
    sessions:"public/sessions"
   }

  devise_for :admin, skip: [:registrations, :passwords],controllers:{
    sessions:"admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/addresse.rb
class Addresse < ApplicationRecord
   belongs_to :customer
   
   def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
   end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :item
   belongs_to :customer
   
   def subtotal
    item.with_tax_price * amount
   end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         def address_display
           '〒' + postal_code + ' ' + address + ' ' + last_name + ' ' + first_name
         end
end

app/models/genre.rb
class Genre < ApplicationRecord
   has_many :items, dependent: :destroy
   # validates :, inclusion: { in: [true, false] }
end

app/models/item.rb
class Item < ApplicationRecord
   has_one_attached :image
   has_many :cart_items, dependent: :destroy
   has_many :order_items, dependent: :destroy
   belongs_to :genre
   
    def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/images.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
    end
    
    def with_tax_price
    (price * 1.1).floor
    end
    
    
end

app/models/order.rb
class Order < ApplicationRecord
   has_many :order_items, dependent: :destroy
   belongs_to :customer
   
   enum payment_method: { credit_card: 0, transfer: 1 }
   enum order_status: { waiting: 0, payment: 1, production: 2, preparation: 3, shipping: 4 }
   
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
   belongs_to :item
   belongs_to :order

   enum production_status: { cannot_start: 0, waiting: 1, production: 2, completion: 3, }

   def with_tax_price
    (purchase_price * 1.1).floor
   end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!, only: [:index,:show,:edit]
  
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    flash[:notice] = "更新しました"
    redirect_to admin_customer_path(@customer.id)
  end

  private

   def customer_params
     params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number,:email,:is_deleted)
   end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!, only: [:index,:edit]
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    flash[:notice] = "登録しました"
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    flash[:notice] = "更新しました"
    redirect_to admin_genres_path
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!, only: [:top]
  
  def top
    @orders = Order.page(params[:page])
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!, only: [:index,:show,:edit,:new]
  
  def index
    @items = Item.page(params[:page]).per(8)
  end

  def new
    @item = Item
    @items = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    flash[:notice] = "登録しました"
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    flash[:notice] = "更新しました"
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!, only: [:show]

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @total_price = 0
    @postage = 800
  end

  def update
    @order = Order.find(params[:id])
    @order_items = OrderItem.where(order_id: params[:id])
    if @order.update(order_params)
    @order_items.update_all(production_status: 1) if @order.order_status == "payment"
    flash[:notice] = "更新しました"
    redirect_to admin_order_path(@order.id)
    end
  end

  private
  def order_params
    params.require(:order).permit(:order_status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?
   protected

    # def after_sign_out_path_for(resource)
    #   admin_path(resource)
    # end

   # def after_sign_out_path_for(resource)
   #    root_path
   #  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class = "container">
      <div class = "row">
        <div class = "col-md-12">
          <div class = "m-5"></div>
            <h2><%= @customer.last_name + @customer.first_name %>さんの会員情報編集</h2>
          </div>
        </div>
        </div>
        <%= form_with model: @customer, url: admin_customer_path do |f| %>
        <div class = "container">
        <div class = "row">
        <div class = "col-md-4 mt-3">会員ID</div>
        <div class = "col-md-8 mt-3"><%= @customer.id %></div>
        <div class = "col-md-3 mt-3">氏名</div>
        <div class = "col-md-1 mt-3">（姓）</div>
        <div class = "col-md-4 mt-3"><%= f.text_field :last_name %></div>
        <div class = "col-md-1 mt-3">（名）</div>
        <div class = "col-md-3 mt-3"><%= f.text_field :first_name %></div>
        <div class = "col-md-3 mt-3">フリガナ</div>
        <div class = "col-md-1 mt-3">（セイ）</div>
        <div class = "col-md-4 mt-3"><%= f.text_field :last_name_kana %></div>
        <div class = "col-md-1 mt-3">（メイ）</div>
        <div class = "col-md-3 mt-3"><%= f.text_field :first_name_kana %></div>
        <div class = "col-md-4 mt-3">郵便番号（ハイフンなし）</div>
        <div class = "col-md-8 mt-3"><%= f.text_field :postal_code %></div>
        <div class = "col-md-4 mt-3">住所</div>
        <div class = "col-md-8 mt-3"><%= f.text_field :address, :size=>"76"  %></div>
        <div class = "col-md-4 mt-3">電話番号（ハイフンなし）</div>
        <div class = "col-md-8 mt-3"><%= f.text_field :telephone_number %></div>
        <div class = "col-md-4 mt-3">メールアドレス</div>
        <div class = "col-md-8 mt-3"><%= f.email_field :email, autofocus: true, autocomplete: "email" %></div>
        <div class = "col-md-4 mt-3">会員ステータス</div>
        <div class = "col-md-8 mt-3">
           <%= f.radio_button :is_deleted, false %>
           <%= f.label :is_deleted, "有効" %>
           <%= f.radio_button :is_deleted, true %>
           <%= f.label :is_deleted, "退会" %>
        </div>
        <div class = "col-4 offset-4">
          <div class = "mt-3">
            <%= f.submit "変更を保存" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    </div>
    </div>

app/views/admin/customers/index.html.erb
<div class = "container">
      <div class = "row">
         <p class = "col-md-12 h3">会員一覧</p>
         <table class="table table-bordered mt-5">
            <thead>
               <tr>
                  <th class="col-md-2">会員ID</th>
                  <th class="col-md-3">氏名</th>
                  <th class="col-md-4">メールアドレス</th>
                  <th class="col-md-３">ステータス</th>
               </tr>
            </thead>
            <tbody>
               <% @customers.each do |customers| %>
               <tr>
                  <td class = "pt-3 h4 text-center"><%= customers.id %></td>
                  <td class = "pt-3 h4 text-center"><%= link_to customers.last_name + customers.first_name, admin_customer_path(customers.id) %></td>
                  <td class = "pt-3 h4 text-center"><%= customers.email %></td>
                  <td class = "pt-3 h4 text-center">
                     <% if customers.is_deleted == false %>
                       有効
                     <% else customers.is_deleted == true %>
                       退会
                     <% end %>
                  </td>
               </tr>
               <% end %>
            </tbody>
         </table>
         <div class = "col-md-12 mt-5 h4 text-center"><%= paginate @customers %></div>
      </div>
   </div>

app/views/admin/customers/show.html.erb
   <div class = "container">
      <div class = "row">
         <p class = "col-md-12 h3"><%= @customer.last_name + @customer.first_name %>さんの会員詳細</p>
         <table class="col table table-bordered">
            <thead>
               <tr>
                  <th class="col-md-3 pt-3 h4 text-center">会員ID</th>
                  <td><%= @customer.id %></td>
               </tr>
               <tr>
                  <th class="col-md-3 pt-3 h4 text-center">氏名</th>
                  <td><%= @customer.last_name + @customer.first_name %></td>
               </tr>
               <tr>
                  <th class="col-md-3 pt-3 h4 text-center">フリガナ</th>
                  <td><%= @customer.last_name_kana + @customer.first_name_kana %></td>
               </tr>
               <tr>
                  <th class="col-md-3 pt-3 h4 text-center">郵便番号</th>
                  <td><%= @customer.postal_code %></td>
               </tr>
               <tr>
                  <th class="col-md-3 pt-3 h4 text-center">住所</th>
                  <td><%= @customer.address %></td>
               </tr>
               <tr>
                  <th class="col-md-3 pt-3 h4 text-center">電話番号</th>
                  <td><%= @customer.telephone_number %></td>
               </tr>
               <tr>
                  <th class="col-md-3 pt-3 h4 text-center">メールアドレス</th>
                  <td><%= @customer.email %></td>
               </tr>
               <tr>
                  <th class="col-md-3 pt-3 h4 text-center">退会ステータス</th>
                  <td><% if @customer.is_deleted == false %>
                       有効
                      <% else @customer.is_deleted == true %>
                       退会
                      <% end %>
                  </td>
               </tr>
            </thead>
         </table>
         <div class = "col-md-12 mt-5 h4 text-center">
            <%= link_to "編集する", edit_admin_customer_path(@customer.id) %>
         </div>
         <div class = "col-md-12 mt-5 h4 text-center">
         </div>
      </div>
   </div>