config/routes.rb
Rails.application.routes.draw do

  scope module: :public do

    resources :addresses,except:[:new,:show]

    get    'orders/new'
    post   'orders/confirm'
    get    'orders/completion'
    resources :orders,only:[:index,:create,:show]


    delete 'cart_items/erase_all' =>   "cart_items#erase"
    resources :cart_items,only:[:index,:create,:destroy,:update]

    patch  'customers/withdraw'
    get    'customers/mypage' =>       "customers#show"
    get    'customers/edit'
    patch  'customers' =>              "customers#update"
    get    'customers/unsubscribe'

    resources :items,only:[:index,:show]

    root to: "homes#top"
    get 'about' => "homes#about"
  end
  namespace :admin do
    resources :order_items,only:[:update]

    resources :orders,only:[:show,:update]

    resources :customers,except:[:destroy,:create,:new]

    resources :genres,except:[:destroy,:new,:show]

    resources :items,except:[:destroy]

    root to: "homes#top"
  end
  devise_for :customers, skip: [:passwords],controllers:{
    registrations:"public/registrations",
    sessions:"public/sessions"
   }

  devise_for :admin, skip: [:registrations, :passwords],controllers:{
    sessions:"admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/addresse.rb
class Addresse < ApplicationRecord
   belongs_to :customer
   
   def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
   end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :item
   belongs_to :customer
   
   def subtotal
    item.with_tax_price * amount
   end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         def address_display
           '〒' + postal_code + ' ' + address + ' ' + last_name + ' ' + first_name
         end
end

app/models/genre.rb
class Genre < ApplicationRecord
   has_many :items, dependent: :destroy
   # validates :, inclusion: { in: [true, false] }
end

app/models/item.rb
class Item < ApplicationRecord
   has_one_attached :image
   has_many :cart_items, dependent: :destroy
   has_many :order_items, dependent: :destroy
   belongs_to :genre
   
    def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/images.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
    end
    
    def with_tax_price
    (price * 1.1).floor
    end
    
    
end

app/models/order.rb
class Order < ApplicationRecord
   has_many :order_items, dependent: :destroy
   belongs_to :customer
   
   enum payment_method: { credit_card: 0, transfer: 1 }
   enum order_status: { waiting: 0, payment: 1, production: 2, preparation: 3, shipping: 4 }
   
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
   belongs_to :item
   belongs_to :order

   enum production_status: { cannot_start: 0, waiting: 1, production: 2, completion: 3, }

   def with_tax_price
    (purchase_price * 1.1).floor
   end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!, only: [:index,:edit]
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    flash[:notice] = "登録しました"
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    flash[:notice] = "更新しました"
    redirect_to admin_genres_path
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!, only: [:top]
  
  def top
    @orders = Order.page(params[:page])
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!, only: [:index,:show,:edit,:new]
  
  def index
    @items = Item.page(params[:page]).per(8)
  end

  def new
    @item = Item
    @items = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    flash[:notice] = "登録しました"
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    flash[:notice] = "更新しました"
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!, only: [:show]

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @total_price = 0
    @postage = 800
  end

  def update
    @order = Order.find(params[:id])
    @order_items = OrderItem.where(order_id: params[:id])
    if @order.update(order_params)
    @order_items.update_all(production_status: 1) if @order.order_status == "payment"
    flash[:notice] = "更新しました"
    redirect_to admin_order_path(@order.id)
    end
  end

  private
  def order_params
    params.require(:order).permit(:order_status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController

  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_in_path_for(resource)
      admin_root_path
  end
  def after_sign_out_path_for(resource)
      admin_root_path
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?
   protected

    # def after_sign_out_path_for(resource)
    #   admin_path(resource)
    # end

   # def after_sign_out_path_for(resource)
   #    root_path
   #  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class = "container">
        <div class = "col-md-12">
          <div class = "m-5"></div>
            <h2>ジャンル編集</h2>
            </div>
        <%= form_with model: @genre, url: admin_genre_path do |f| %>
        <div class = "row">
        <div class = "col-md-2 mt-5">ジャンル名</div>
        <div class = "col-md-3 mt-5"><%= f.text_field :name %></div>
        <div class = "col-md-7 mt-5"><%= f.submit'変更を保存' %></div>
        <% end %>
     </div>
</div>

app/views/admin/genres/index.html.erb
<div class = "container">
        <div class = "col-md-12">
          <div class = "m-5"></div>
            <h2>ジャンル一覧・追加</h2>
            </div>
        <%= form_with model: @genre, url: admin_genres_path do |f| %>
        <div class = "row">
        <div class = "col-md-2 mt-5">ジャンル名</div>
        <div class = "col-md-3 mt-5"><%= f.text_field :name %></div>
        <div class = "col-md-7 mt-5"><%= f.submit'新規登録' %></div>
        <% end %>
     </div>
     <div class = "row">
        <table class="table table-bordered mt-5">
            <thead>
               <tr>
                  <th class="col-4">ジャンル</th>
                  <th class="col-8"></th>
               </tr>
            </thead>
            <tbody>
               <% @genres.each do |genres| %>
               <tr>
                  <td class = "pt-3 h4 text-center"><%= genres.name %></td>
                  <td class = "pt-3 h4 text-center"><%= link_to "編集する", edit_admin_genre_path(genres.id) %></td>
               </tr>
               <% end %>
            </tbody>
         </table>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class = "container">
      <div class = "row">
        <div class = "col-md-12">
          <div class = "m-5"></div>
            <h2>商品編集</h2>
          </div>
        <%= form_with model: @item, url: admin_item_path do |f| %>
        <div class = "row">
        <div class = "offset-md-2 col-md-2 mt-3">商品画像</div>
        <div class = "col-md-8 mt-3"><%= f.file_field :image, accept: "image/*" %></div>
        <div class = "offset-md-2 col-md-2 mt-3">商品名</div>
        <div class = "col-md-8 mt-3"><%= f.text_field :name %></div>
        <div class = "offset-md-2 col-md-2 mt-3">商品説明</div>
        <div class = "col-md-8 mt-3"><%= f.text_area :introduction %></div>
        <div class = "offset-md-2 col-md-2 mt-3">ジャンル</div>
        <div class = "col-md-8 mt-3"><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %></div>
        <div class = "offset-md-2 col-md-2 mt-3">税抜価格</div>
        <div class = "col-md-8 mt-3"><%= f.number_field :price %>円</div>
        <div class = "offset-md-2 col-md-2 mt-3">販売ステータス</div>
        <div class = "col-md-8 mt-3">
            <%= f.radio_button :is_active, true %>
            <%= f.label :is_active, "販売中" %>
            <%= f.radio_button :is_active, false %>
            <%= f.label :is_active, "販売停止中" %>
        </div>
        <div class = "col-md-12 mt-3 text-center"><%= f.submit '変更を保存' %></div>
        <% end %>
     </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<body>
   <div class = "container">
      <div class = "row">
         <p class = "col-md-8 h3">商品一覧</p>
         <p class = "col-md-4 h5"><%= link_to "商品追加", new_admin_item_path  %></p>
         <table class="table table-bordered mt-5">
            <thead>
               <tr>
                  <th class="col-md-2">商品ID</th>
                  <th class="col-md-4">商品名</th>
                  <th class="col-md-2">税抜価格</th>
                  <th class="col-md-2">ジャンル</th>
                  <th class="col-md-2">ステータス</th>
               </tr>
            </thead>
            <tbody>
               <% @items.each do |items| %>
               <tr>
                  <td class = "pt-3 h4 text-center"><%= items.id %></td>
                  <td>
                     <%= link_to admin_item_path(items.id) do %>
                     <%= items.name %>
                     <% end %>
                  </td>
                  <td class = "pt-3 h4 text-center"><%= items.price %></td>
                  <td class = "pt-3 h4 text-center"><%= items.genre.name %></td>
                  <td class = "pt-3 h4 text-center">
                     <% if items.is_active == true %>
                        販売中
                     <% else items.is_active == false %>
                        販売停止中
                     <% end %>
                  </td>
               </tr>
               <% end %>
            </tbody>
         </table>
         <div class = "col-md-12 mt-5 h4 text-center"><%= paginate @items %></div>
      </div>
   </div>
</body>

app/views/admin/items/new.html.erb
<div class = "container">
      <div class = "row">
        <div class = "col-md-12">
          <div class = "m-5"></div>
            <h2>商品新規登録</h2>
          </div>
        <%= form_with model: @item, url: admin_items_path do |f| %>
        <div class = "row">
        <div class = "offset-md-2 col-md-2 mt-3">商品画像</div>
        <div class = "col-md-8 mt-3"><%= f.file_field :image, accept: "image/*" %></div>
        <div class = "offset-md-2 col-md-2 mt-3">商品名</div>
        <div class = "col-md-8 mt-3"><%= f.text_field :name %></div>
        <div class = "offset-md-2 col-md-2 mt-3">商品説明</div>
        <div class = "col-md-8 mt-3"><%= f.text_area :introduction %></div>
        <div class = "offset-md-2 col-md-2 mt-3">ジャンル</div>
        <div class = "col-md-8 mt-3"><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %></div>
        <div class = "offset-md-2 col-md-2 mt-3">税抜価格</div>
        <div class = "col-md-8 mt-3"><%= f.number_field :price %>円</div>
        <div class = "offset-md-2 col-md-2 mt-3">販売ステータス</div>
        <div class = "col-md-8 mt-3">
            <%= f.radio_button :is_active, true %>
            <%= f.label :is_active, "販売中" %>
            <%= f.radio_button :is_active, false %>
            <%= f.label :is_active, "販売停止中" %>
        </div>
        <div class = "col-md-12 mt-3 text-center"><%= f.submit '新規登録' %></div>
        <% end %>
     </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class = "container">
      <div class = "row">
        <div class = "col-md-12">
          <div class = "m-5"></div>
            <h2>商品詳細</h2>
          </div>
           <div class = " col-md-4 mt-3"><%= image_tag @item.image, size: '300x250'  %></div>
        <div class = "col-md-8 mt-3">
           <div class = "row">
              <div class = "col-md-4">
                 商品名
              </div>
              <div class = "col-md-8">
                 <%= @item.name %>
              </div>
           </div>
           <div class = "row">
              <div class = "col-md-4 mt-3">
                 商品説明
              </div>
              <div class = "col-md-8 mt-3">
                 <%= @item.introduction %>
              </div>
           </div>
           <div class = "row">
              <div class = "col-md-4 mt-3">
                 ジャンル
              </div>
              <div class = "col-md-8 mt-3">
                 <%= @item.genre.name %>
              </div>
           </div>
           <div class = "row">
              <div class = "col-md-4 mt-3">
                 税込価格<br>
                 (税抜価格)
              </div>
              <div class = "col-md-8 mt-3">
                 <%= (@item.price * 1.1).floor %>(<%= @item.price %>)円
              </div>
           </div>
           <div class = "row">
              <div class = " col-md-4 mt-3">
                 販売ステータス
              </div>
              <div class = "col-md-8 mt-3">
                 <% if @item.is_active == true %>
                    販売中
                 <% elsif @item.is_active == false  %>
                    売切れ
              <% end %>
              </div>
           </div>
           <div class = "row">
              <div class = "col-md-12 mt-3">
                 <%= link_to "編集する", edit_admin_item_path(params[:id]) %>
              </div>
            </div>
        </div>
     </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class = "container">
      <div class = "row">
        <div class = "col-md-12">
          <div class = "m-5"></div>
            <h2>注文履歴詳細</h2>
          </div>
        </div>
        <div class = "row">
        <div class = "col-md-4 mt-3">購入者</div>
        <div class = "col-md-8 mt-3"><%= @order.customer.last_name + @order.customer.first_name %></div>
        <div class = "col-md-4 mt-3">注文日</div>
        <div class = "col-md-8 mt-3"><%= @order.created_at.strftime("%Y-%m-%d" ) %></div>
        <div class = "col-md-4 mt-3">配送先</div>
        <div class = "col-md-8 mt-3">
           <%= "〒" + @order.postal_code + @order.address %><br>
           <%= @order.customer.last_name + @order.customer.first_name %>
        </div>
        <div class = "col-md-4 mt-3">支払方法</div>
        <div class = "col-md-8 mt-3"><%= @order.payment_method_i18n %></div>
        <div class = "col-md-4 mt-3">注文ステータス</div>
        <div class = "col-md-8 mt-3">
           <%= form_with model: @order, url: admin_order_path(@order.id) do |f|  %>
           <%= f.select :order_status, Order.order_statuses.keys.map {|k| [I18n.t("enums.order.order_status.#{k}"), k]} %>
           <%= f.submit '更新' %>
           <% end %>
        </div>
        </div>
        <div class = "row">
           <table class="col-md-12 table table-bordered mt-5">
            <thead>
               <tr>
                  <th class="col-md-3">商品名</th>
                  <th class="col-md-2">単価（税込）</th>
                  <th class="col-md-1">数量</th>
                  <th class="col-md-2">小計</th>
                  <th class="col-md-2">製作ステータス</th>
                  <th class="col-md-2"></th>
               </tr>
            </thead>
            <tbody>
                <% @order_items.each do |order_items| %>
               <tr>
                  <td class = "pt-3 h4 text-center"><%= order_items.item.name %></td>
                  <td class = "pt-3 h4 text-center"><%= order_items.with_tax_price %></td>
                  <td class = "pt-3 h4 text-center"><%= order_items.quantity %></td>
                  <td class = "pt-3 h4 text-center"><%= order_items.with_tax_price * order_items.quantity %></td>
                  <%= form_with model: order_items, url: admin_order_item_path(order_items.id) do |f|  %>
                  <td class = "pt-3 h4 text-center"><%= f.select :production_status, OrderItem.production_statuses.keys.map {|k| [I18n.t("enums.order_item.production_status.#{k}"), k]} %></td>
                  <td class = "pt-3 h4 text-center"><%= f.submit '更新' %></td>
                  <% end %>
                  <% @total_price += order_items.with_tax_price * order_items.quantity %>
               </tr>
               <% end %>
            </tbody>
         </table>
         <div class="col-md-12">
            <div class = "row">
               <div class="col-md-6 h4">商品合計</div>
               <div class="col-md-6 h4"><%= @total_price %></div>
            </div>
            <div class = "row">
               <div class="col-md-6 h4">送料</div>
               <div class="col-md-6 h4"><%= @postage %></div>
            </div>
            <div class = "row">
               <div class="col-md-6 h4">請求金額合計</div>
               <div class="col-md-6 h4"><%= @total_price += @postage %></div>
            </div>
         </div>
        </div>
      </div>