config/routes.rb
Rails.application.routes.draw do

  scope module: :public do

    resources :addresses,except:[:new,:show]

    get    'orders/new'
    post   'orders/confirm'
    get    'orders/completion'
    resources :orders,only:[:index,:create,:show]


    delete 'cart_items/erase_all' =>   "cart_items#erase"
    resources :cart_items,only:[:index,:create,:destroy,:update]

    patch  'customers/withdraw'
    get    'customers/mypage' =>       "customers#show"
    get    'customers/edit'
    patch  'customers' =>              "customers#update"
    get    'customers/unsubscribe'

    resources :items,only:[:index,:show]

    root to: "homes#top"
    get 'about' => "homes#about"
  end
  namespace :admin do
    resources :order_items,only:[:update]

    resources :orders,only:[:show,:update]

    resources :customers,except:[:destroy,:create,:new]

    resources :genres,except:[:destroy,:new,:show]

    resources :items,except:[:destroy]

    root to: "homes#top"
  end
  devise_for :customers, skip: [:passwords],controllers:{
    registrations:"public/registrations",
    sessions:"public/sessions"
   }

  devise_for :admin, skip: [:registrations, :passwords],controllers:{
    sessions:"admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/addresse.rb
class Addresse < ApplicationRecord
   belongs_to :customer
   
   def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
   end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :item
   belongs_to :customer
   
   def subtotal
    item.with_tax_price * amount
   end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         def address_display
           '〒' + postal_code + ' ' + address + ' ' + last_name + ' ' + first_name
         end
end

app/models/genre.rb
class Genre < ApplicationRecord
   has_many :items, dependent: :destroy
   # validates :, inclusion: { in: [true, false] }
end

app/models/item.rb
class Item < ApplicationRecord
   has_one_attached :image
   has_many :cart_items, dependent: :destroy
   has_many :order_items, dependent: :destroy
   belongs_to :genre
   
    def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/images.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
    end
    
    def with_tax_price
    (price * 1.1).floor
    end
    
    
end

app/models/order.rb
class Order < ApplicationRecord
   has_many :order_items, dependent: :destroy
   belongs_to :customer
   
   enum payment_method: { credit_card: 0, transfer: 1 }
   enum order_status: { waiting: 0, payment: 1, production: 2, preparation: 3, shipping: 4 }
   
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
   belongs_to :item
   belongs_to :order

   enum production_status: { cannot_start: 0, waiting: 1, production: 2, completion: 3, }

   def with_tax_price
    (purchase_price * 1.1).floor
   end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!, only: [:index,:edit]
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    flash[:notice] = "登録しました"
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    flash[:notice] = "更新しました"
    redirect_to admin_genres_path
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!, only: [:top]
  
  def top
    @orders = Order.page(params[:page])
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!, only: [:index,:show,:edit,:new]
  
  def index
    @items = Item.page(params[:page]).per(8)
  end

  def new
    @item = Item
    @items = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    flash[:notice] = "登録しました"
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    flash[:notice] = "更新しました"
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?
   protected

    # def after_sign_out_path_for(resource)
    #   admin_path(resource)
    # end

   # def after_sign_out_path_for(resource)
   #    root_path
   #  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <h1 class = "center navbar-brand ml-5">
          Nagano Cake
        </h1>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto mr-5">
            <% if admin_signed_in? %>
              <li class="nav-item active">
                <div>
                  <%= link_to admin_root_path, class:"nav-link" do %>
                  <%= "注文履歴一覧" %>
                  <% end %>
                  <span class="sr-only">(current)</span>
                </div>
              </li>
              <li class="nav-item">
                <div>
                  <%= link_to admin_items_path, class:"nav-link"  do %>
                  <%= "商品一覧" %>
                  <% end %>
                </div>
              </li>
              <li class="nav-item">
                <div>
                  <%= link_to admin_genres_path, class:"nav-link" do %>
                  <%= "ジャンル一覧" %>
                  <% end %>
                </div>
              </li>
              <li class="nav-item">
                <div>
                  <%= link_to admin_customers_path, class:"nav-link"  do %>
                  <%= "会員一覧" %>
                  <% end %>
                </div>
              </li>
              <li class="nav-item">
                <div>
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"nav-link" %>
                </div>
              </li>
              <% elsif customer_signed_in? %>
              <li class="nav-item active">
                <div>
                  <%= link_to "TOPページ", root_path, class:"nav-link" %>
                  <span class="sr-only">(current)</span>
                </div>
              </li>
              <li class="nav-item">
                <div>
                  <%= link_to "商品一覧画面", items_path, class:"nav-link" %>
                </div>
              </li>
              <li class="nav-item">
                <div>
                  <%= link_to "カート画面",  cart_items_path, class:"nav-link" %>
                </div>
              </li>
              <li class="nav-item">
                <div>
                  <%= link_to "マイページ", customers_mypage_path, class:"nav-link" %>
                </div>
              </li>
              <li class="nav-item">
                <div>
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"nav-link" %>
                </div>
              </li>
              <% else %>
              <li class="nav-item">
                <div>
                  <%= link_to "about", about_path, class:"nav-link" %>
                </div>
              </li>
              <li class="nav-item">
                <div>
                  <%= link_to "商品一覧", root_path, class:"nav-link" %>
                  <span class="sr-only">(current)</span>
                </div>
              </li>
              <li class="nav-item">
                <div>
                  <%= link_to "新規登録", new_customer_registration_path, class:"nav-link" %>
                </div>
              </li>
              <li class="nav-item">
                <div>
                  <%= link_to "ログイン", new_customer_session_path, class:"nav-link" %>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
      <p id="notice"><%= flash[:notice] %></p>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>